const express = require("express");
const mongoose = require("mongoose");
const routes = require("./routes");
const app = express();
const path = require("path");
const server = require('http').createServer(app)
const io = require('socket.io').listen(server)
const axios = require("axios")

require("dotenv").config();

const PORT = process.env.PORT || 3001;

// Define middleware here
app.use(express.urlencoded({ extended: true }));
app.use(express.json());

// Add routes, both API and view
app.use(routes);

// Connect to the Mongo DB
mongoose
    // .connect("mongodb://localhost/greenpoint_test", {
      
  .connect(process.env.MONGODB_URI, {
    useNewUrlParser: true,
    useCreateIndex: true,
    useUnifiedTopology: true,
    useFindAndModify: false
  })
  .then(() => console.log("MongoDB Connected..."))
  .catch(err => console.log(err));

// Serve up static assets (usually on heroku)
if (process.env.NODE_ENV === "production") {
  // Set static folder
  app.use(express.static("client/build"));

  app.get("*", (req, res) => {
    res.sendFile(path.resolve(__dirname, "client", "build", "index.html"));
  });
}

// Start the API server
server.listen(PORT, function() {
  console.log(`🌎  ==> API Server now listening on PORT ${PORT}!`);
});

io.sockets.on('connection', function (socket) {
  console.log("A user just connected");
  socket.emit("Welcome", {message:"Welcome to our site"})

  setInterval(() => getWeather(socket), 60000)

  socket.on('diconnect', function () {
    console.log("A user disconnected");

  })

  socket.on("Test", function(msg){
    console.log("Message: " + msg)
    socket.emit("Reply", {reply: "This reply generated by the server"})
  })


})

const getWeather = async socket => {
  console.log("I'm getting the weather")
  socket.emit("Weather", "Here is the weather")
  // try {
  //   const res =await axios.get (
  //     "https://api.darksky.net/forecast/d9b62331cf144fc78ad5473806d97872/38.9072,-77.0369"

  //   );
   
  // } catch (error) {
  //   console.log(error)
  // }
}
